apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
  namespace: logoutput-ns
spec:
  type: ClusterIP
  selector:
    app: logimages
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000