apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: logoutput-ns
spec:
  type: ClusterIP
  selector:
    app: logimages
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3001