apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project-ns
spec:
  type: ClusterIP
  selector:
    app: todo-project 
  ports:
    - protocol: TCP
      port: 1233  
      targetPort: 3003 