apiVersion: apps/v1
kind: Deployment
metadata:
  name: logimages-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logimages
  template:
    metadata:
      labels:
        app: logimages
    spec:
      containers:
        - name: log-output
          image: sonawei/log-output:v2.01
        - name: pingpong
          image: sonawei/pingpong:v2.01
