name: 'Delete Environment on Branch Deletion'

on:
  delete:
    branches-ignore:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }} # TODO: update to your Google Cloud project ID
  GKE_CLUSTER: 'autopilot-cluster-3' # TODO: update to your cluster name
  GKE_ZONE: 'us-central1' # TODO: update to your cluster zone
  DEPLOYMENT_NAME: 'todo-project-dep' # TODO: update to your deployment name

jobs:
  setup-build-publish-deploy:
    name: 'Delete Environment When Branch is Deleted'
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2' # google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: 'Delete Kubernetes resources'
        run: |
          kubectl delete namespace ${GITHUB_REF#refs/heads/} --ignore-not-found=true
          echo "Deleted namespace: ${GITHUB_REF#refs/heads/}"

      - name: 'Delete Docker images'
        run: |
          gcloud container images delete "gcr.io/$PROJECT_ID/todo-app:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" --quiet || true
          gcloud container images delete "gcr.io/$PROJECT_ID/todo-backend:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" --quiet || true
          echo "Deleted Docker images for branch: ${GITHUB_REF#refs/heads/}"