apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/postgres-configmap.yaml
  - manifests/postgres-secret.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/statefulset.yaml
  - manifests/todoapp-service.yaml
  - manifests/todobackend-service.yaml
  - manifests/ingress.yaml
images:
  - name: TODO_APP_IMAGE
    newName: sonawei/todo-app
    newTag: v2.08
  - name: TODO_BACKEND_IMAGE
    newName: sonawei/todo-backend
    newTag: v2.10