# persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-claim
spec:
  storageClassName: project-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
